import type { Barber, BusinessText, Service } from '@/lib/content-types'

export const seedServices: Service[] = [
  {
    _id: 'seed-corte',
    slug: 'corte-de-pelo',
    name: 'Corte de pelo',
    description: 'Corte de cabello personalizado a tu estilo.',
    price: 14,
    durationMinutes: 30,
    featured: true,
    active: true,
    order: 10,
  },
  {
    _id: 'seed-barba-maquina',
    slug: 'arreglo-de-barba-maquina',
    name: 'Arreglo de barba (máquina)',
    description: 'Perfilado y arreglo profesional de barba.',
    price: 8,
    durationMinutes: 30,
    featured: false,
    active: true,
    order: 20,
  },
  {
    _id: 'seed-corte-barba',
    slug: 'corte-y-barba',
    name: 'Corte + Barba',
    description: 'Servicio completo de corte de pelo y arreglo de barba.',
    price: 20,
    durationMinutes: 60,
    featured: true,
    active: true,
    order: 30,
  },
  {
    _id: 'seed-barba-navaja',
    slug: 'arreglo-de-barba-navaja',
    name: 'Arreglo de barba (cuchilla y afeitado a navaja)',
    description:
      'Disfruta de la tradición del afeitado a navaja, un servicio que combina técnica, cuidado y atención al detalle.',
    price: 10,
    durationMinutes: 30,
    featured: true,
    active: true,
    order: 40,
  },
  {
    _id: 'seed-permanente',
    slug: 'permanente',
    name: 'Permanente',
    description:
      'Creamos rizos y ondas personalizados, diseñados a medida según la textura de tu cabello y la imagen que deseas proyectar. Trabajamos con fórmulas de alta gama que respetan la fibra capilar, aportando suavidad, brillo y un acabado sofisticado.',
    price: 60,
    durationMinutes: 120,
    featured: false,
    active: true,
    order: 50,
  },
  {
    _id: 'seed-mechas',
    slug: 'mechas',
    name: 'Mechas',
    description:
      'Consigue un acabado luminoso y cuidado con nuestro servicio de decoloración. Adaptamos el proceso a tu tipo de cabello para lograr un resultado limpio, uniforme y favorecedor.',
    price: 60,
    durationMinutes: 120,
    featured: false,
    active: true,
    order: 60,
  },
  {
    _id: 'seed-cejas',
    slug: 'arreglo-de-cejas',
    name: 'Arreglo de cejas',
    description: null,
    price: 2,
    durationMinutes: 5,
    featured: false,
    active: true,
    order: 70,
  },
]

export const seedBarbers: Barber[] = [
  {
    _id: 'seed-hassan',
    name: 'Hassan',
    role: 'Barbero',
    bio: null,
    photo: {
      url: '/equipo/hassan.jpeg',
      alt: 'Hassan, de pie con los brazos cruzados junto al sillón de la barbería',
      aspectRatio: 755 / 1021,
      lqip: null,
    },
    instagram: null,
    acceptsBookings: true,
    vacationFrom: null,
    vacationTo: null,
    order: 10,
  },
  {
    _id: 'seed-mohammed',
    name: 'Mohammed',
    role: 'Barbero',
    bio: null,
    photo: {
      url: '/equipo/mohammed.jpeg',
      alt: 'Mohammed, con los brazos cruzados delante de los espejos de la barbería',
      aspectRatio: 1123 / 1037,
      lqip: null,
    },
    instagram: null,
    acceptsBookings: true,
    vacationFrom: null,
    vacationTo: null,
    order: 20,
  },
  {
    _id: 'seed-nassim',
    name: 'Nassim',
    role: 'Barbero',
    bio: null,
    photo: {
      url: '/equipo/nassim.jpeg',
      alt: 'Nassim, sentado en el sofá de la zona de espera de la barbería',
      aspectRatio: 1056 / 811,
      lqip: null,
    },
    instagram: null,
    acceptsBookings: true,
    vacationFrom: null,
    vacationTo: null,
    order: 30,
  },
]

export const seedBusinessText: BusinessText = {
  heroHeadline: 'Tu estilo',
  heroLead: 'Nuestra pasión',
  aboutTitle: 'La barbería',
  aboutBody: [],
  walkInsWelcome: true,
}
